-   repo: git@git.yelpcorp.com:mirrors/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
        language_version: python3.6
    -   id: end-of-file-fixer
        language_version: python3.6
        exclude: ^\.activate\.sh$
    -   id: autopep8-wrapper
        language_version: python3.6
    -   id: check-docstring-first
        language_version: python3.6
    -   id: check-executables-have-shebangs
        language_version: python3.6
    -   id: check-merge-conflict
        language_version: python3.6
    -   id: check-yaml
        language_version: python3.6
    -   id: debug-statements
        language_version: python3.6
    -   id: double-quote-string-fixer
        language_version: python3.6
    -   id: name-tests-test
        language_version: python3.6
    -   id: flake8
        language_version: python3.6
    -   id: check-added-large-files
        language_version: python3.6
        exclude: ^\.activate\.sh$
    -   id: check-byte-order-marker
        language_version: python3.6
-   repo: git@git.yelpcorp.com:mirrors/asottile/reorder_python_imports
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python3.6
-   repo: git@git.yelpcorp.com:mirrors/asottile/pyupgrade
    sha: v1.1.2-1
    hooks:
    -   id: pyupgrade
        language_version: python3.6
